import { FormEvent } from "react";
import { Mail, MessageCircle } from "lucide-react";

export default function Contact() {
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const message = `Hello ALRAHEEM COLLECTION 786, I need help with an order or a product.\n\nName: ${form.get("name")}\nEmail: ${form.get("email")}\nMessage: ${form.get("message")}`;
    window.open(`https://wa.me/923361243334?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer");
  };
  return <section className="min-h-[70vh] bg-[#fffdf9] py-12 md:py-20"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow"><span />A note from the studio</p><h1 className="font-serif text-5xl leading-[.92] tracking-[-.04em] text-[#123f72] md:text-7xl">We are here to <i className="text-[#bb492d]">help.</i></h1><p className="mt-6 max-w-md text-sm leading-7 text-slate-500">Need assistance with a piece, delivery or an existing order? Send a message directly to the collection team on WhatsApp.</p><div className="mt-8 grid gap-4"><div className="flex items-start gap-3 text-sm leading-6 text-[#123f72]"><Mail size={18} className="mt-1 shrink-0 text-[#bb492d]" /> Shopify checkout orders appear in the owner’s Shopify Admin app under <b>Orders</b>.</div><div className="flex items-start gap-3 text-sm leading-6 text-[#123f72]"><MessageCircle size={18} className="mt-1 shrink-0 text-[#bb492d]" /> Direct-order and support messages arrive in the ALRAHEEM WhatsApp Business chat.</div></div></div><form onSubmit={submit} className="border border-[#d8d0c2] bg-white p-7 md:p-10"><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-[#bb492d]">WhatsApp support</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-[10px] font-extrabold uppercase tracking-[.13em] text-[#647182]">Name<input required name="name" className="border border-[#d8d0c2] px-3 py-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-[#123f72]" placeholder="Your name" /></label><label className="grid gap-2 text-[10px] font-extrabold uppercase tracking-[.13em] text-[#647182]">Email<input required type="email" name="email" className="border border-[#d8d0c2] px-3 py-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-[#123f72]" placeholder="you@example.com" /></label></div><label className="mt-5 grid gap-2 text-[10px] font-extrabold uppercase tracking-[.13em] text-[#647182]">Message<textarea required name="message" rows={6} className="resize-y border border-[#d8d0c2] px-3 py-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-[#123f72]" placeholder="How can we help?" /></label><button type="submit" className="button-primary mt-6"><MessageCircle size={15} /> Continue on WhatsApp</button><p className="mt-4 text-xs leading-6 text-slate-500">Submitting opens WhatsApp with your message ready to send.</p></form></div></section>;
}
