import { Copy, Gift, ShieldCheck, Share2 } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

export default function Referral() {
  const { data, isLoading } = trpc.customer.me.useQuery(undefined, { retry: false });
  if (isLoading) return <section className="container grid min-h-[55vh] place-items-center"><p className="text-sm text-slate-500">Loading your referral details…</p></section>;
  if (!data?.profile) return <section className="container grid min-h-[55vh] place-items-center text-center"><div><p className="eyebrow justify-center"><span />Referral rewards</p><h1 className="mt-4 font-serif text-5xl text-[#123f72]">Share with <i>care.</i></h1><p className="mx-auto mt-4 max-w-md text-sm leading-7 text-slate-600">Sign in to receive a personal referral link and see rewards that are earned after qualifying paid purchases.</p><Link href="/account" className="button-primary mt-7">Sign in to continue</Link></div></section>;
  const link = `${window.location.origin}/account?ref=${data.profile.referral_code}`;
  const copy = async () => { try { await navigator.clipboard.writeText(link); toast.success("Referral link copied."); } catch { toast.error("Copy is unavailable. Please select the link manually."); } };
  return <section className="bg-[#fffdf9] py-12 md:py-18"><div className="container max-w-4xl"><p className="eyebrow"><span />Your referral rewards</p><h1 className="mt-3 font-serif text-5xl leading-[.95] text-[#123f72]">Share the <i>collection.</i></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-600">Your reward is a one-use 17% discount, created only after a new customer joins through your link and completes a qualifying paid order. There are no rewards for clicks, signups, or unpaid orders.</p><div className="mt-8 border border-[#123f72] bg-[#eef3f7] p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-[#123f72]">Your personal referral link</p><div className="mt-3 flex flex-col gap-3 sm:flex-row"><code className="min-w-0 flex-1 overflow-x-auto bg-white px-3 py-3 text-sm text-[#123f72]">{link}</code><button type="button" onClick={copy} className="button-primary"><Copy size={15} /> Copy link</button></div></div><div className="mt-10 grid gap-4 md:grid-cols-3"><article className="border border-[#d8d0c2] p-5"><Share2 className="text-[#bb492d]" /><h2 className="mt-4 font-serif text-2xl text-[#123f72]">1. Share</h2><p className="mt-2 text-sm leading-6 text-slate-500">Send only your personal link to friends and family.</p></article><article className="border border-[#d8d0c2] p-5"><ShieldCheck className="text-[#bb492d]" /><h2 className="mt-4 font-serif text-2xl text-[#123f72]">2. Verify</h2><p className="mt-2 text-sm leading-6 text-slate-500">The order is verified after it is paid and matched securely.</p></article><article className="border border-[#d8d0c2] p-5"><Gift className="text-[#bb492d]" /><h2 className="mt-4 font-serif text-2xl text-[#123f72]">3. Reward</h2><p className="mt-2 text-sm leading-6 text-slate-500">A one-use 17% reward code appears in your account.</p></article></div>{data.rewards.length ? <section className="mt-10 border-t border-[#d8d0c2] pt-7"><h2 className="font-serif text-3xl text-[#123f72]">Your issued rewards</h2><div className="mt-4 space-y-3">{data.rewards.map(reward => <article key={reward.discount_code} className="flex flex-wrap items-center justify-between gap-3 border border-[#d8d0c2] p-4"><div><p className="font-bold text-[#123f72]">{reward.discount_code}</p><p className="mt-1 text-xs uppercase tracking-[.1em] text-slate-500">{reward.status}</p></div><p className="font-bold text-[#bb492d]">{reward.discount_percent}% off</p></article>)}</div></section> : null}</div></section>;
}
