import { useState } from "react";
import { PackageCheck, Search } from "lucide-react";

export default function TrackOrder() {
  const queryReference = typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("reference")?.trim() ?? "";
  const [reference, setReference] = useState(queryReference);
  const [submitted, setSubmitted] = useState(Boolean(queryReference));
  return <section className="min-h-[70vh] bg-[#fffdf9] py-12 md:py-20"><div className="container grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div className="bg-[#123f72] p-8 text-[#f9f6ef] md:p-12"><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-[#f3b49d]">Order care</p><h1 className="mt-4 font-serif text-5xl leading-[.92] tracking-[-.04em] md:text-7xl">Follow your <i className="text-[#f3b49d]">selection.</i></h1><p className="mt-6 max-w-sm text-sm leading-7 text-[#cbd6e2]">Enter the reference sent after checkout and we will direct you to the latest fulfilment update once your order is in motion.</p></div><div className="flex flex-col justify-center border border-[#d8d0c2] p-8 md:p-12"><PackageCheck size={30} className="text-[#bb492d]" /><h2 className="mt-5 font-serif text-4xl text-[#123f72]">Track an order.</h2><form className="mt-7" onSubmit={event => { event.preventDefault(); const trimmedReference = reference.trim(); if (!trimmedReference) return; window.history.replaceState(null, "", `/track-order?reference=${encodeURIComponent(trimmedReference)}`); setSubmitted(true); }}><label className="text-[10px] font-extrabold uppercase tracking-[.13em] text-[#647182]" htmlFor="order-reference">Order reference</label><div className="mt-2 flex border border-[#d8d0c2] bg-white"><input id="order-reference" required value={reference} onChange={event => setReference(event.target.value)} placeholder="Example: AR786-1234" className="min-w-0 flex-1 bg-transparent px-4 py-3 text-sm outline-none" /><button type="submit" className="bg-[#123f72] px-4 text-white" aria-label="Track order"><Search size={18} /></button></div></form>{submitted && <div className="mt-6 border-l-2 border-[#bb492d] bg-[#f5f1e9] p-4 text-sm leading-6 text-[#42566d]"><b className="text-[#123f72]">Reference received.</b> We have prepared an update request for <b className="text-[#123f72]">{reference || queryReference}</b>. Live fulfilment details will appear here after checkout orders are available in the store.</div>}</div></div></section>;
}
